### ISSUE TITLE
My thoughts

### ISSUE THREAD

**Issue by Shirimasen** [torifat/xiaomi-mi-air-purifier#18]
Setting fan speed to 0% turns off device, then why we need on/off switch? I would prefer to have option to set fan to 0% while keeping device running so I can read temperature etc. Also built in modes (Auto, Night, 1, 2, 3, Manual) are useless because there is no way to access them.

I think that there should be:
1. on/off switch
2. screen on/off switch
3. parental controls on/off switch
3. mode selection (buttons just like in Mi Home app)
4. fan speed control (active only on manual mode, 0% just turns off the fan)

Also UI via Homebridge ui feels really laggy. When I turn on device it takes like 10 seconds to show up that device is on.

My ultimate goal is to make my own "Automatic" mode. Because built in auto mode is cranking up the fan way too late. I would like just to set simple rules like: 1-3 -> 0% fan, 3-5 -> 10%, 5-10 -> 30%, 10-20 -> 50% etc. It's a shame that something that simple requires setting up so many things. If there is a way to override somehow built in auto mode with my own settings that would be awesome.

**Comment by torifat** [comment]
> Setting fan speed to 0% turns off device, then why we need on/off switch? I would prefer to have option to set fan to 0% while keeping device running so I can read temperature etc.

You can still read temperature or humidity in that state unless you are unplugging your purifier. Also, I just set the speed to 0, the device itself decides the state.

> Also built in modes (Auto, Night, 1, 2, 3, Manual) are useless because there is no way to access them.

Apple only supports two modes inside HomeKit.

> Also UI via Homebridge ui feels really laggy. When I turn on device it takes like 10 seconds to show up that device in on.

I haven't used the Homebridge UI. It works ok in Home app. I will have a look.
