### ISSUE TITLE
I got the error like this: 

### ISSUE THREAD

**Issue by boomchatchat** [torifat/xiaomi-mi-air-purifier#226]
I got the error like this: 
How to fix it?

[11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info.
_[Removed rest of the log because they don't provide any additional value. - Rifat]_

**Comment by torifat** [comment]
Can you please share your version of `homebridge-xiaomi-mi-air-purifier`?

**Comment by Csehla** [comment]
> I got the error like this: How to fix it?
> 
> [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Target Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.mode is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside read handler for characteristic: device.fanSpeed is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Air Quality': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'PM2.5 Density': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: device.temperature is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:12:58 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Relative Humidity': Unhandled error thrown inside read handler for characteristic: device.rh is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.power is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Target Air Purifier State': Unhandled error thrown inside read handler for characteristic: device.mode is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside read handler for characteristic: device.fanSpeed is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Air Quality': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'PM2.5 Density': Unhandled error thrown inside read handler for characteristic: device.pm2_5 is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: device.temperature is not a function. See https://git.io/JtMGR for more info. [11/18/2021, 11:13:16 PM] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Current Relative Humidity': Unhandled error thrown inside read handler for characteristic: device.rh is not a function. See https://git.io/JtMGR for more info.

I have the same problem!

**Comment by torifat** [comment]
@Csehla your issue is similar to #223

**Comment by Dane03** [comment]
@torifat Thanks for your effort here. 
I am constantly getting errors like 

20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.
[20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.
[20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.

Version is homebridge-xiaomi-mi-air-purifier v2.0.0
NPM 8.1.4
Node 16.13

Using Xiaomi Air Purifier 2h and Pro H

**Comment by guesq** [comment]
> Filter Life Level

same here.
I find the values of property 'filter_life' and 'child_lock' are 'undefined'.
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-life-level.ts#L17
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-change-indication.ts#L28
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/lock-physical-controls.ts#L24

So I comment these lines out for now, then return some determined values and these errors are gone. There might be something wrong with getting these properties values.

**Comment by guesq** [comment]
> @torifat Thanks for your effort here. I am constantly getting errors like
> 
> 20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.
> 
> Version is homebridge-xiaomi-mi-air-purifier v2.0.0 NPM 8.1.4 Node 16.13
> 
> Using Xiaomi Air Purifier 2h and Pro H



> @torifat Thanks for your effort here. I am constantly getting errors like
> 
> 20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.
> 
> Version is homebridge-xiaomi-mi-air-purifier v2.0.0 NPM 8.1.4 Node 16.13
> 
> Using Xiaomi Air Purifier 2h and Pro H

same here.
I find the values of property 'filter_life' and 'child_lock' are 'undefined'.
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-life-level.ts#L17
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-change-indication.ts#L28
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/lock-physical-controls.ts#L24

So I comment these lines out for now, then return some determined values and these errors are gone. There might be something wrong with getting these properties values.

**Comment by guesq** [comment]
> @torifat Thanks for your effort here. I am constantly getting errors like
> 
> 20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.
> 
> Version is homebridge-xiaomi-mi-air-purifier v2.0.0 NPM 8.1.4 Node 16.13
> 
> Using Xiaomi Air Purifier 2h and Pro H

same here.
I find the values of property 'filter_life' and 'child_lock' are 'undefined'.
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-life-level.ts#L17
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-change-indication.ts#L28
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/lock-physical-controls.ts#L24

So I comment these lines out for now, then return some determined values and these errors are gone. There might be something wrong with getting these properties values.

**Comment by guesq** [comment]
> @torifat Thanks for your effort here. I am constantly getting errors like
> 
> 20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Lock Physical Controls': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info. [20/11/2021, 19:08:09] [homebridge-xiaomi-mi-air-purifier] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'value'). See https://git.io/JtMGR for more info.
> 
> Version is homebridge-xiaomi-mi-air-purifier v2.0.0 NPM 8.1.4 Node 16.13
> 
> Using Xiaomi Air Purifier 2h and Pro H

Same here.
I find the values of property 'filter_life' and 'child_lock' are 'undefined'.
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-life-level.ts#L17
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/filter-change-indication.ts#L28
https://github.com/torifat/xiaomi-mi-air-purifier/blob/f6c9fb8211a8e8306b48b6f452cac6d726051dea/src/characteristics/air-purifier/lock-physical-controls.ts#L24

So I comment these lines out for now, then return some determined values and these errors are gone. There might be something wrong with getting these properties values.

**Comment by torifat** [comment]
@Dane03 @guesq seems like you folks are having a different problem. So I will create a separate issue for this. In the worse case, I can automatically disable `filter_life` and `child_lock` for 2H and Pro H. 

@guesq did you try to turn them off in settings before commenting out the code?
<img width="476" alt="Screen Shot 2021-11-21 at 4 36 12 pm" src="https://user-images.githubusercontent.com/208544/142751094-b2185db9-12c0-4346-b9e7-1bdd1da733cd.png">

**Comment by guesq** [comment]
> @Dane03 @guesq seems like you folks are having a different problem. So I will create a separate issue for this. In the worse case, I can automatically disable `filter_life` and `child_lock` for 2H and Pro H.
> 
> @guesq did you try to turn them off in settings before commenting out the code? <img alt="Screen Shot 2021-11-21 at 4 36 12 pm" width="476" src="https://user-images.githubusercontent.com/208544/142751094-b2185db9-12c0-4346-b9e7-1bdd1da733cd.png">

@torifat Thanks for your reply.
I'm using Xiaomi Air Purifier 2H. This is my settings:
![Mi-Air-Purifier-Settings](https://user-images.githubusercontent.com/2208637/142751671-0fc01848-4ce3-46b5-a478-b7e34407cdd0.png)
I did not turn 'Child Lock' on and only got the errors about 'Filter Life Level' and 'Filter Change Indication'. So I just commented out the lines with 'filter_life' property. I also tested turning on 'Child Lock' and got the errors about 'Lock Physical Controls'.

**Comment by torifat** [comment]
@guesq Ah! thank you. My bad! It's `filter_life` and not Air Quality. Also, thanks for confirming that the setting works for **Child Lock**.

**Comment by luluhoc** [comment]
https://github.com/torifat/xiaomi-mi-air-purifier/pull/233

made a pull request fixing this bug

**Comment by torifat** [comment]
Closing this in favour of #229
