### ISSUE TITLE
No response in HomeKit fan speed

### ISSUE THREAD

**Issue by BrapBrapp2** [torifat/xiaomi-mi-air-purifier#241]
On Mi air purifier 2S, when changing fan speed in HomeKit it gives no responses! Otherwise great plug-in! Running it on Hoobs.

**Comment by torifat** [comment]
I will fix it soon. This has been already reported in https://github.com/torifat/xiaomi-mi-air-purifier/issues/229#issuecomment-976657941. Please follow that issue. I'm closing this one as duplicate.
