### ISSUE TITLE
Buttons for Auto/Nightmode

### ISSUE THREAD

**Issue by fynnsh** [torifat/xiaomi-mi-air-purifier#25]
Im Missing this Feature with all Plugins for Homebridge. Is there a way to implement the Automode so you can switch between manual control and the auto mode?

**Comment by ifeign** [comment]
Auto mode is within the accessory itself, click on the air purifier and scroll down.

**Comment by torifat** [comment]
@fynnsh Apple only support auto/manual mode. Try what @ifeign suggested.
