### ISSUE TITLE
Air purifier does not respond - problem with plugin

### ISSUE THREAD

**Issue by Csehla** [torifat/xiaomi-mi-air-purifier#65]
I have an issue in my log: This plugin slows down Homebridge. I use it in a child bridge mode, but not work... what is the problem?

**Comment by somesanAdrian** [comment]
I'm having the same issues, the device is not responding in Homekit app and in the homebridge status it says: _"This plugin slows down Homebridge. The read handler for the characteristic 'Active' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info."_

**Comment by kutdenis** [comment]
> I'm having the same issues, the device is not responding in Homekit app and in the homebridge status it says: _"This plugin slows down Homebridge. The read handler for the characteristic 'Active' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info."_

Same problem with the plugin

**Comment by JamesBedwell** [comment]
Same issue. My 2S purifier is no longer responding, same issue for maybe a week now, tried updating plugin and homebridge but didn't fix the issue. Following

**Comment by digitalbugs** [comment]
Same issue
Following

**Comment by sinnfeinn** [comment]
Same issue: [homebridge-xiaomi-mi-air-purifier] This plugin slows down Homebridge. The read handler for the characteristic 'PM2.5 Density' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
Tried to add it as a childbridge but cant add it in homekit.

**Comment by mrykin** [comment]
same problem:

[3/6/2021, 1:35:54 AM] [homebridge-xiaomi-mi-air-purifier] This plugin generated a warning from the characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

AND

[3/6/2021, 1:33:38 AM] [homebridge-xiaomi-mi-air-purifier] This plugin generated a warning from the characteristic 'Lock Physical Controls': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/6/2021, 1:33:40 AM] [homebridge-xiaomi-mi-air-purifier] This plugin generated a warning from the characteristic 'Target Air Purifier State': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

**Comment by moonpen** [comment]
Have the same issue too, following.

**Comment by drz01** [comment]
@Csehla You were the first to report the issue 15 days ago. According to the [commit timeline](https://github.com/torifat/xiaomi-mi-air-purifier/commits/master) Dependabot bumped homebridge to 1.3.1 16 days ago. I am hoping to pin down the origin of this bug so we can testing for it.

**Comment by JamesBedwell** [comment]
> @Csehla You were the first to report the issue 15 days ago. According to the [commit timeline](https://github.com/torifat/xiaomi-mi-air-purifier/commits/master) Dependabot bumped homebridge to 1.3.1 16 days ago. I am hoping to pin down the origin of this bug so we can start testing for it.

hi @drz01 I experienced this issue on an earlier version of Homebridge (1.1.x), not just the latest release. So it might not strictly be something in 1.3.1.

**Comment by sinnfeinn** [comment]
Homebridge states in [https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings](https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings) :

> This plugin slows down Homebridge...
> If you see this message in the logs it means the plugin was very slow to respond from a request to get the current status or update the state of an accessory. Plugins that respond slowly can impact the responsiveness of the entire bridge.
> 
> 👤 If you're an end user, you should report this issue to the plugin developer.
> 
> Moving slow plugins to a Child Bridge can prevent it from impacting other plugins.
> 🧑‍💻 If you're the plugin developer:
> 
> Make sure the callback() is called.
> Make sure you are catching any possible exceptions and still calling the callback() even if an error occurred.
> If the action does take some time to complete, adjust your plugin code to return the callback() instantly, and call characteristic.updateValue once the action has completed.

I tried moving it to a child bridge but it wont add it to my iOS Homekit.

**Comment by drz01** [comment]
I got that far as well. This repo may be dormant; I'll look into the issue some more...

**Comment by marcpodi** [comment]
This plugin works 20% of the time. I had to use Mi Home app to turn on the Air Purifier.

**Comment by torifat** [comment]
Can you please try the new version? The old one wasn't working properly with Homebrige 1.3.

**Comment by Csehla** [comment]
I try it. I have a new problem (but the plugin works now): This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of undefined. See https://git.io/JtMGR for more info.

**Comment by torifat** [comment]
Hey @Csehla, please create a new issue for the filter level problem please 🙏🏽. Also, it would be nice to mention your device in the issue.
