### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by adamrzanek** [torifat/xiaomi-mi-air-purifier#9]
So far your plugin doesn't work for 2h and 3h for me... Nut i'm hoping to use it in the future :)

**Comment by torifat** [comment]
Can you please share your device models (`zhimi.airpurifier.mb3`) and the errors you are getting.

For 2H, I created #10 and will fix it soon.

And, I'm not sure where did you find a 4H device - https://www.google.com/search?hl=en&q=xiaomi%20mi%20air%20purifier%204h

**Comment by adamrzanek** [comment]
@torifat sorry i mean 3h - my bad

**Comment by adamrzanek** [comment]
Did you consider to add led controll and pm2,5 breakpoints?

**Comment by torifat** [comment]
> sorry i mean 3h - my bad

Can you please share the error you are getting

> Did you consider to add led control and pm2,5 breakpoints?

I thought about adding option to define custom breakpoints for pm2.5. But, I haven't found a good way to add LED control. I didn't like the way other plugins added it as a lightbulb 💡.

**Comment by adamrzanek** [comment]
It’s now working with 3h. I think it was interfering with other plugin. Thanks for making great work!

**Comment by torifat** [comment]
You are welcome. I will give you a ping once I have a fix for 2H.

**Comment by adamrzanek** [comment]
> > sorry i mean 3h - my bad
> 
> Can you please share the error you are getting
> 
> > Did you consider to add led control and pm2,5 breakpoints?
> 
> I thought about adding option to define custom breakpoints for pm2.5. But, I haven't found a good way to add LED control. I didn't like the way other plugins added it as a lightbulb 💡.

I think it doesn’t look bad with this plugin 

![5A437ED0-38C4-4F19-B3FA-84A0D9EABC6C](https://user-images.githubusercontent.com/65444919/103709604-33b25e80-4fb3-11eb-9737-ddba79017024.png)

**Comment by torifat** [comment]
> I think it doesn’t look bad with this plugin

ok, you convinced me. I will add it soon 😀
